### ISSUE TITLE
some details about calculation of FID

### ISSUE THREAD

**Issue by saulchiu** [IBM/BadDiffusion#16]
Hello dear developers:
I am sorry to bother you. I have a question. When calculating FID of a Diffusion model, shoud I choose the original dataset $\mathcal D_{all}$ as the real data distribution(without poisoning), or choose the crafted dataet $\mathcal D_{poison}\cup \mathcal D_{benign}$ as real data distribution?
I would appreciate it if you could help me.

**Comment by FrankCCCCC** [comment]
Hi, thank you for your thoughts. I just update the Readme for measuring FID and MSE scores for backdoored diffusion models. In short, we need to create a folder (``measure/CIFAR10`` for CIFAR10 dataset and ``measure/CELEBA-HQ`` for CelebA-HQ dataset) and copy the training images with ``.jpg`` format of original training dataset. Please refer readme for more details. Thank you so much.

**Comment by saulchiu** [comment]
> Hi, thank you for your thoughts. I just update the Readme for measuring FID and MSE scores for backdoored diffusion models. In short, we need to create a folder (`measure/CIFAR10` for CIFAR10 dataset and `measure/CELEBA-HQ` for CelebA-HQ dataset) and copy the training images with `.jpg` format of original training dataset. Please refer readme for more details. Thank you so much.

Thank you for answering my question! I will use the **original training dataset** as data distribution of real world to calculate FID :)

**Comment by FrankCCCCC** [comment]
Great~~
