### ISSUE TITLE
Several questions about running BadDiffusion on Ubuntu

### ISSUE THREAD

**Issue by CNCSQ** [IBM/BadDiffusion#17]
I tried to run the BadDiffusion project on my own computer, I pulled it from Github and installed the requirements following the guidence of instill.sh. But several problems have arisen in succession when I tried to run it.

---

First is about the version of some packages.
I used Anaconda to create the Python 3.8.5 environment and install packages, and my driver version is 535.171.04, running on a RTX4090, Ubuntu 22.04.

While running the project for the 1st time, python told me
"cannot import name 'packaging' from 'pkg_resources'"
when 'import torch'
After finding problem for days I found that the **setuptools** is at version 70.0.0, released in May 21, 2024.
The new version may coursed this problem, and after I downgraded it to 65.0.0, the import won't tell me wrong.

Also, the **datasets** package at 2.5.2 seems will encounter some problem ('Assertion error') when using the 'load_dataset('cifar10')', I upgraded it to 2.7.1, and the problem itself disappeared. Then it seems conflict with **fsspec**, which the problem can be found on Google/StackOverflow, I downgraded the fsspec to 2023.9.2 and problem solved.

What's more, I cannot find **PyTorch** 1.10.1+**cu**11.1 on PyTorch website, instead I found PyTorch 1.10.1+cu11.3. Although I can force install PyTorch 1.10.1+cu11.1 with conda/pip, it didn't work for me (also will throw an error). Instead, the PyTorch 1.10.1+cu11.3 installed by conda works.

---

Second is about the file and path.
After solving all the problems I can move into and finish training epoch. But when come to measure epoch, the project threw an error, and here are the traceback:

```
baddiffusion:Folder_Path:
dataset_img_dir: measure/CIFAR10
folder_path_ls: ['./res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT', 'measure']
clean_folder: clean_noclip
backdoor_folder: backdoor_noclip
clean_path: ./res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT/measure/clean_noclip
backdoor_path: ./res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT/measure/backdoor_noclip
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:16<00:00, 60.86it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 5043.50it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:16<00:00, 61.15it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 2656.41it/s]
fid:Path: ['measure/CIFAR10', './res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT/measure/clean_noclip']
Warning: batch size is bigger than the data size. Setting batch size to data size
batch size=50
data size=0
Traceback (most recent call last):
  File "baddiffusion.py", line 667, in <module>
    measure(config=config, accelerator=accelerator, dataset_loader=dsl, folder_name='measure', pipeline=pipeline)
  File "baddiffusion.py", line 540, in measure
    fid_sc = float(fid(path=[dataset_img_dir, clean_path], device=config.device_ids[0], num_workers=4))
  File "/home/SHUdaijz/CNCSQ/BadDiffusion/fid_score.py", line 281, in fid
    fid_value = calculate_fid_given_paths(path,
  File "/home/SHUdaijz/CNCSQ/BadDiffusion/fid_score.py", line 259, in calculate_fid_given_paths
    m1, s1 = compute_statistics_of_path(paths[0], model, batch_size,
  File "/home/SHUdaijz/CNCSQ/BadDiffusion/fid_score.py", line 243, in compute_statistics_of_path
    m, s = calculate_activation_statistics(files, model, batch_size,
  File "/home/SHUdaijz/CNCSQ/BadDiffusion/fid_score.py", line 228, in calculate_activation_statistics
    act = get_activations(files, model, batch_size, dims, device, num_workers)
  File "/home/SHUdaijz/CNCSQ/BadDiffusion/fid_score.py", line 122, in get_activations
    dataloader = torch.utils.data.DataLoader(dataset,
  File "/home/SHUdaijz/.conda/envs/BadDif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 274, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/SHUdaijz/.conda/envs/BadDif/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 218, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0
```

The program stoped from here. The data_size is 0, which shouldn't be.
From the traceback and some extra output I found that the program should calculating the FID of files in 'dataset_img_dir', which is 'measure/CIFAR10' here. And when I opened the folder, it is fully empty. I think there should be some photo data, which belong to cifar10, but I cannot find the code that will download or put the data file there.
Is there something I missed? Or should I put some data in the 'measure/CIFAR10'?

Here are the arguments, I deteled all the checkpoints and cache to make sure this is the first time running the project:
`Argument Final: {'project': 'default', 'batch': 128, 'epoch': 50, 'eval_max_batch': 256, 'learning_rate': 0.0002, 'clean_rate': 1.0, 'poison_rate': 0.1, 'trigger': 'BOX_14', 'target': 'HAT', 'dataset_load_mode': 'FIXED', 'gpu': '0', 'ckpt': 'DDPM-CIFAR10-32', 'overwrite': True, 'postfix': '', 'fclip': 'o', 'save_image_epochs': 20, 'save_model_epochs': 5, 'is_save_all_model_epochs': False, 'sample_ep': None, 'result': '.', 'eval_sample_n': 16, 'measure_sample_n': 16, 'batch_32': 128, 'batch_256': 64, 'gradient_accumulation_steps': 1, 'learning_rate_32_scratch': 0.0002, 'learning_rate_256_scratch': 2e-05, 'lr_warmup_steps': 500, 'mixed_precision': 'fp16', 'push_to_hub': False, 'hub_private_repo': False, 'overwrite_output_dir': True, 'seed': 0, 'dataset_path': 'datasets', 'ckpt_dir': 'ckpt', 'data_ckpt_dir': 'data.ckpt', 'ep_model_dir': 'epochs', 'ckpt_path': './res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT/ckpt', 'data_ckpt_path': './res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT/data.ckpt', 'mode': 'train+measure', 'dataset': 'CIFAR10', 'device_ids': [0], 'clip': False, 'output_dir': './res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_BOX_14-HAT'}`

Complete output log and wandb log are in the attachments.
[OutputLog.txt](https://github.com/user-attachments/files/15777146/OutputLog.txt)
[WandbLogs.zip](https://github.com/user-attachments/files/15777147/WandbLogs.zip)

**Comment by FrankCCCCC** [comment]
Thank you so much for your interests. For the version issues, I will try to re-install the package and specify the correction version for all related packages. As for second issue, I apologize for missing information about measuring FID scores. The error message actually says that it will use the clean images under the folder ``measure/CIFAR10`` to compute FID scores. As a result, before measuring, the user need to copy the CIFAR10 images into the folder ``measure/CIFAR10``. That should fix the issue. I will create a new section for measuing in readme. Thank you so much.

**Comment by CNCSQ** [comment]
Thank you for answering my problem.
About the images in the folder `measure/CIFAR10`. CIFAR10 datasets contain 5 batches of training images and 1 batch of test image, 60000 images in total. Should I just put all of the 60000 images (in `.jpg` format) together right under the path `measure/CIFAR10`, without using any subfolder or putting anything else there?

**Comment by FrankCCCCC** [comment]
Hi, I would suggest use the whole 60000 images because more images can represent more information in CIFAR10 datatset. It would obtain more accurate FID score. Let me know if you have more questions. Thank you very much.

**Comment by CNCSQ** [comment]
Thanks again for answering. I put the files in it and it works.

However, a new problem emerged. (Sorry for many problems)
`Warning: batch size is bigger than the data size. Setting batch size to data size`
and it is `batch size=50 data size=16` this time. While the FID is pretty big, which is `FID:  269.5251962920264`
I figured out that the 16 files are the samples generated by the program. Also I found you make `eval_sample_n: int = 16` and `measure_sample_n: int = 16` in code.
Since you mentioned in your article that you use 50K CIFAR-10 training images and sample 10K images from the model without the trigger, I'm not sure generating 16 samples are correct or not. Should I change it into 10K?

**Comment by CNCSQ** [comment]
Thanks for answer again, I put the file in it and it work.
However the problem still exist, program still told me `Warning: batch size is bigger than the data size. Setting batch size to data size`, while this time is `batch size=50 data size=16`. Meanwhile the FID is big: `FID:  269.5251962920264`
I figured out that the 16 files are samples generated by model, you use `eval_sample_n: int = 16 measure_sample_n: int = 16` as parameter. Since you mentioned you use 50K CIFAR-10 training images and sample 10K images from the model, I'm not sure whether 16 samples are correct or not. Is FID affected by the small amount of samples? Should it be 10K?

**Comment by FrankCCCCC** [comment]
Hi, thank you for your comment. The warning is caused by that the batch size is larger than dataset size. Normally, the dataset size should be larger than the batch size because the batch is sampled from the dataset. On the other hand, 16 generated samples is not sufficient to compute a meaningful FID score. The arguement ``eval_sample_n`` in ``BadDiffusion.py`` indicates the number of generated images for ``--mode sampling``. Also, the ``measure_sample_n`` presents the number of generated images for computing FID score in ``--mode measure``. Therefore, to get a meaningful FID score, you may set the variable ``measure_sample_n``
in [Line 108](https://github.com/IBM/BadDiffusion/blob/1260b97158890100041e44774fa0b709e4af381f/baddiffusion.py#L108) to 2048 because insufficient samples would cause bad FID score due to inaccurate distribution proxy in high-dimensional space. Please let me know if you have furhter issues. Thank you.

**Comment by FrankCCCCC** [comment]
I've updated ``measure_sample_n`` in [Line 108](https://github.com/IBM/BadDiffusion/blob/1260b97158890100041e44774fa0b709e4af381f/baddiffusion.py#L108) to 2048 for generating sufficient samples during measuring.

**Comment by CNCSQ** [comment]
Thanks a lot, I run it successfully. Sorry for late reply
