### ISSUE TITLE
Question about the minimum GPU requirements for the experiment

### ISSUE THREAD

**Issue by byerose** [IBM/BadDiffusion#2]
Hello, I am very interested in the project and would like to try running and training your model. However, since my GPU configuration is relatively low (2 × NVIDIA TITAN Xp 12GB), I am worried that it may not meet the minimum configuration requirements for the experiment.

**Comment by pinyuchen** [comment]
Hello @byerose. In this case, you may want to choose a smaller batch size to fit into your hardware constraints. Thanks.
