### ISSUE TITLE
Missing module datasets.load_dataset

### ISSUE THREAD

**Issue by ybwang119** [IBM/BadDiffusion#6]
Hi there! When running the command `python baddiffusion.py --project default --mode train+measure --dataset CIFAR10 --batch 128 --epoch 50 --poison_rate 0.1 --trigger BOX_14 --target HAT --ckpt DDPM-CIFAR10-32 --fclip o -o --gpu 0`, we found the error:
`File "/data/yanbo.wang/BadDiffusion/baddiffusion.py", line 12, in <module>
    from dataset import DatasetLoader, Backdoor, ImagePathDataset
  File "/data/yanbo.wang/BadDiffusion/dataset.py", line 9, in <module>
    from datasets import load_dataset, concatenate_datasets
ImportError: cannot import name 'load_dataset' from 'datasets' (unknown location)`

Seems that after running the bash command and mkdir datasets, we do not have related functions named `load_dataset`, `concatenate_datasets`.

Hope we could get the reply.

**Comment by FrankCCCCC** [comment]
Hi, sorry for late reply. Line 9 in file ``dataset.py`` would load Huggingface ``datasets`` package. Thus, please install it via ``pip install datasets``.

https://huggingface.co/docs/datasets/installation
