### ISSUE TITLE
Can your code be used to insert backdoor on CELEBA dataset?

### ISSUE THREAD

**Issue by mo666666** [IBM/BadDiffusion#9]
Notice that in `dataset.py`, loading CELEBA dataset is supported. What should I do if I want to perform experiments on CELEBA dataset?

**Comment by FrankCCCCC** [comment]
Hi, we've conducted experiments on CelebA-HQ but not CelebA. I am not sure whether it would work on CelebA dataset or not.  I will test on it in the future.
